### ISSUE TITLE
Dependency warning when patching

### ISSUE THREAD

**Issue by iamed2** [invenia/Mocking.jl#64]
Example:
```
┌ Warning: Package Mocking does not have LibPQ in its dependencies:
│ - If you have Mocking checked out for development and have
│   added LibPQ as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Mocking
└ Loading LibPQ into Mocking from project dependency, future warnings for Mocking are suppressed.
```

This happens because Mocking evals into a module it doesn't depend on.

**Comment by omus** [comment]
Will be fixed by #63. The reason for this warning was due to us using external packages inside of generated submodules within Mocking. We could have alternatively fixed this by generating a submodule at the location of the patch but that has its own set of issues (combining multiple patches for example).
