### ISSUE TITLE
Confused about latest release

### ISSUE THREAD

**Issue by GregPlowman** [invenia/Mocking.jl#96]
Latest release seems to be 0.7.4
However master `Project.toml` shows version 0.7.3. Also there seems to be more recent commits since 0.7.4?
My installation using default `Pkg.add` shows 0.7.3.

**Comment by omus** [comment]
The 0.7.4 release was found to have a major bug so that release was yanked from the registry and reverted in https://github.com/invenia/Mocking.jl/pull/93. The latest changes on master are effectively just documentation changes which is why we haven't made a new release.

That said we may want to make a 0.7.5 release just so that 0.7.4 stops appearing to be the latest release.

**Comment by GregPlowman** [comment]
OK. Thanks for the explanation!
